# -------------------------------------
# Theme and Site Settings
# -------------------------------------
remote_theme: jekyll/minima
title: Your Name | Professional Portfolio
email: your.email@example.com
description: >-
  This is the professional portfolio of [Your Name]. Find my CV, written reports,
  and contact information here.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# -------------------------------------
# Minima Theme Customization (Optional)
# -------------------------------------
minima:
  social_links:
    github: your-github-username
    linkedin: your-linkedin-username 
    # Add other social links (e.g., twitter, dribbble) here if needed

header_pages:
  # This list controls what appears in your navigation bar.
  - index.md
  - cv.md