# Hugo GitHub Pages Deployment Action
name: Deploy Hugo site to GitHub Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push events
  push:
    branches:
      - main # Set your primary branch name (e.g., main, master)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment
permissions:
  contents: read
  pages: write
  id-token: write

# The deployment process
jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: '0.128.2' # Specify the Hugo version (Extended is required for the Academic template)
      
    steps:
      # 1. Checkout the source code
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes (if they are a submodule)
          fetch-depth: 0    # Fetch all history for proper git functionality

      # 2. Install Hugo Extended
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      # 3. Build the Hugo site
      - name: Build Site
        run: hugo --gc --minify
      
      # 4. Upload the 'public' folder as an artifact
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public # The directory containing the built site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4